services:
  _defaults:
    public: true

  advent_of_code.2021.1_1:
    class: App\Services\AdventOfCode2021_1_1
    arguments:
      - '@logger'
      - '%kernel.project_dir%'

  advent_of_code.2021.1_2:
    class: App\Services\AdventOfCode2021_1_2
    arguments:
      - '@logger'
      - '%kernel.project_dir%'

  advent_of_code.2021.2_1:
    class: App\Services\AdventOfCode2021_2_1
    arguments:
      - '@logger'
      - '%kernel.project_dir%'

  advent_of_code.2021.2_2:
    class: App\Services\AdventOfCode2021_2_2
    arguments:
      - '@logger'
      - '%kernel.project_dir%'

  advent_of_code.2021.3_1:
    class: App\Services\AdventOfCode2021_3_1
    arguments:
      - '@logger'
      - '%kernel.project_dir%'

  advent_of_code.2021.3_2:
    class: App\Services\AdventOfCode2021_3_2
    arguments:
      - '@logger'
      - '%kernel.project_dir%'